package ai;

import structures.basic.Board;
import structures.basic.Card;

import java.util.Collections;
import java.util.List;

/**
 * AIPlayer implements an AI which can analyse the positions on the board, calculate different actions,
 * and execute the actions one by one over the board. The actions it can perform includes moving a unit from one tile to another,
 * selecting a unit and then using it to attack an enemy unit, cast a card from its hand, etc.
 */
public class AIPlayer {
    /**
     * This is the reference of the whole board
     */
    private Board board;
    /**
     * This collection contains all the action that the AI could perform
     */
    List<Action> actions = Collections.emptyList();
    /**
     * This collection contains all the card that AI could play
     */
    List<Card> hand = Collections.emptyList();

    /**
     * The health of the AI avatar
     */
    int health = 0;
    /**
     * The mana the AI own
     */
    int mana = 0;

    /**
     * AI will need a reference to board to analyse its position and a list of cards which it will use to play the game.
     * @param board reference to a board instance
     * @param deck the list of cards it will use to play the game
     */
    AIPlayer(Board board, List<Card> deck) {
        this.board = board;
        this.hand = deck;
    }

    /**
     * This function is for AI to execute asynchronously
     */
    public void update() {
        searchAction();
        performAction();
    }

    /**
     * The search action method will analyse the AI's position on the board and then find appropriate actions it should perform.
     * The actions it can perform will be stored in the class variable 'actions'.
     */
    private void searchAction() {
        //Create a list of actions to be performed
    }

    /**
     * The perform action method will execute the action generated by search action method.
     * The list of action will be cleared after executing all the actions to prepare for next turn.
     */
    private void performAction() {
        //Execute actions and then clear the list
    }
}
